### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by An7ar35**
Basic markdowns from the original documentation made for use with `slatedocs` along with a few extras.

_Still needs a bit more but created the PR so @segler-alex can review/comment with more granularity._

### CODE REVIEW

**Comment by An7ar35** [comment]
@segler-alex All JSON, XML, CSV, M3U and PLS code added where appropriate now.

I can remove the `slatedocs` code leaving only the settings file, logo and markdown if you'd like since, I assume, you will likely pull that in its own repo as per their documentation.

Let me know if you want anything edited/added. Cheers.

**Comment by segler-alex** [comment]
thanks for all your work!!!

how do i create the docs?

**Comment by segler-alex** [comment]
i think i can remove mdbook dependency again, correct?

**Comment by An7ar35** [comment]
My pleasure!

Using docker: either pull the docker image or create it (see [link](https://github.com/slatedocs/slate/wiki/Using-Slate-in-Docker) for more details) then just run the generator from the `doc/` directory (see example cmd inside the `docker_run.sh` file I added in `docs/`).

Yes, `mdbook` can go now as far as I'm aware.

**Comment by segler-alex** [comment]
i think this section is missing:
"Example XSPF playlist with extension field"
could you add this as well?

**Comment by An7ar35** [comment]
> i think this section is missing: "Example XSPF playlist with extension field" could you add this as well?

My bad. Documentation #136 PR created.

**Pull request merged**
